# Configuration file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#  - "pypy" fails to install numpy

install:
    # Backport of new unittest features for Python 2.6.
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    # Real dependencies (numpy and matplotlib) expressed in the package.
    - python setup.py install

script: python setup.py test
