# Configuration file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#  - "pypy" fails to install numpy

# Install dependencies
# Need no more than numpy and matplotlib which are expressed dependencies in
# the package. Matplotlib however fails to automatically install one of its
# dependency which is thus expressed in our requirements.txt (tornado).
install: pip install -r requirements.txt

# Run tests.
script: python setup.py test
