# Configuration file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#  - "pypy" fails to install numpy

install:
    - sudo apt-get -qq update
    - sudo apt-get install -y gfortran libatlas-base-dev  # For scipy.
    # Backport of new unittest features for Python 2.6.
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    # Not an usage dependency, only required to test tutorials.
    - pip install matplotlib
    - python setup.py install

script: python setup.py test
